version: "3.9"

services:

  backend1:
    build: ./backend
    container_name: backend1
    ports:
      - "4001:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - secure-net

  backend2:
    build: ./backend
    container_name: backend2
    ports:
      - "4002:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - secure-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - secure-net

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - secure-net

  nginx:
    image: nginx:stable
    container_name: nginx-balancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/certs
      - ./frontend:/usr/share/nginx/html
    ports:
      - "443:443"
    depends_on:
      - backend1
      - backend2
      - frontend
    networks:
      - secure-net

networks:
  secure-net:

volumes:
  mongo-data:
