version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: securetask-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/securetaskdb
    depends_on:
      - mongo
    networks:
      - securetask-net

  mongo:
    image: mongo:latest
    container_name: securetask-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks:
      - securetask-net

networks:
  securetask-net:
